### PR TITLE
fix: access request error handling with no security

### LINKED ISSUE #762: Requesting a device token when security is not enabled results in HTTP status 500
My SensESP code currently tries to unconditionally request a token if none is set. This is probably incorrect behavior, but in any case, the server doesn't take it well:

```
Mar 28 20:14:14 hurma signalk-server[5506]: ::ffff:192.168.9.130 - - [28/Mar/2019:18:14:14 +0000] "POST /signalk/v1/access/requests HTTP/1.1" 500 148 "-" "ESP8266HTTPClient"
Mar 28 20:14:14 hurma signalk-server[5506]: TypeError: app.securityStrategy.requestAccess is not a function
Mar 28 20:14:14 hurma signalk-server[5506]:     at app.post (/opt/signalk-server/lib/serverroutes.js:259:8)
Mar 28 20:14:14 hurma signalk-server[5506]:     at Layer.handle [as handle_request] (/opt/signalk-server/node_modules/express/lib/router/layer.js:95:5)
Mar 28 20:14:14 hurma signalk-server[5506]:     at next (/opt/signalk-server/node_modules/express/lib/router/route.js:137:13)
Mar 28 20:14:14 hurma signalk-server[5506]:     at Route.dispatch (/opt/signalk-server/node_modules/express/lib/router/route.js:112:3)
Mar 28 20:14:14 hurma signalk-server[5506]:     at Layer.handle [as handle_request] (/opt/signalk-server/node_modules/express/lib/router/layer.js:95:5)
Mar 28 20:14:14 hurma signalk-server[5506]:     at /opt/signalk-server/node_modules/express/lib/router/index.js:281:22
Mar 28 20:14:14 hurma signalk-server[5506]:     at Function.process_params (/opt/signalk-server/node_modules/express/lib/router/index.js:335:12)
Mar 28 20:14:14 hurma signalk-server[5506]:     at next (/opt/signalk-server/node_modules/express/lib/router/index.js:275:10)
Mar 28 20:14:14 hurma signalk-server[5506]:     at Layer.handle [as handle_request] (/opt/signalk-server/node_modules/express/lib/router/layer.js:91:12)
Mar 28 20:14:14 hurma signalk-server[5506]:     at trim_prefix (/opt/signalk-server/node_modules/express/lib/router/index.js:317:13)
```

Expected: possibly a 40x error code.

### PR DESCRIPTION
**Pull request by tkurki**
Return 404 with a nice error message if security is not configured
but a client tries to request access.

Fixes #762.

### CODE REVIEW

File: lib/security.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ function getSecurityConfig (app, forceRead = false) {
       return JSON.parse(optionsAsString)
     } catch (e) {
       console.error('Could not parse security config')
-      console.error(e)
+      console.error(e.message)
```
Comment (sbender9) [inline lib/security.js:73]: Why this change? I like the previous way because you get a stack trace along with the message.

Comment (tkurki) [reply lib/security.js:73]: To get rid of the stack trace ;-). I did not like something pretty ok, like unconfigured security, throwing stacktraces. The previous line's error message pinpoints where in code the error happens and there are only so many ways the code block in question can fail.

It could be that I am doing the wrong thing here and we should test if security is configured in some other way so that no stacktraces are flying around.
